version: '3'
services:
  # spins up a local blockchain on port 8545
  ganache:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"
  # spins up react app on port 3000
  react-app:
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true

